Updated  nightly build for fixes and logging

diff --git a/file_roots/auto_setup/nightly_bld b/file_roots/auto_setup/nightly_bld
--- a/file_roots/auto_setup/nightly_bld
+++ b/file_roots/auto_setup/nightly_bld
@@ -5,6 +5,37 @@
 # write new top.sls file containing it, 
 # then everyone can get it from that sls file and pillar get
 
+## helper functions
+
+_timestamp() {
+    date "+%Y-%m-%d %H:%M:%S:"
+}
+
+_log() {
+    echo "$1" | sed "s/^/$(_timestamp) /" >>"${LOGGING}"
+}
+
+# Both echo and log
+_display() {
+    echo "$1"
+    _log "$1" 
+}
+
+_error() {
+    msg="ERROR: $1"
+    echo "$msg" 1>&2
+    echo "$(_timestamp) $msg" >>"${LOGGING}"
+    echo "One or more errors found. See ${LOGGING} for details." 1>&2
+    exit 1
+}
+
+_warning() {
+    msg="WARNING: $1"
+    echo "$msg" 1>&2
+    echo "$(_timestamp) $msg" >>"${LOGGING}"
+}
+
+
 _usage() {
     echo ""
 ##    echo "usage: ${0}  [-h|--help] [-m|--minion <minion_to_use>] [ [-b|--branch <branch_to_build>] | [-t|--tag <tag>] ]"
@@ -31,7 +62,7 @@ _usage() {
     echo ""
 }
 
-vERBOSE=false
+VERBOSE=0
 DEBUG=false
 USAGE_HELP=false
 LOG_MODE='debug'
@@ -41,7 +72,6 @@ RELEASE_BRANCH='2016.11'
 ## minion resident on Salt-Master node
 CODE_MINION='m7m'
 
-##    -v | --verbose ) VERBOSE=true; shift ;;
 ##    -d | --debug )  DEBUG=true; shift ;;
 ##    -l | --log )  LOG_MODE="$2"; shift 2 ;;
 ##    -t | --tag ) RELEASE_TAG="$2"; shift 2 ;;
@@ -54,6 +84,7 @@ while true; do
     -b | --branch ) RELEASE_BRANCH="$2"; shift 2 ;;
     -h | --help ) USAGE_HELP=true; shift ;;
     -m | --minion ) CODE_MINION="$2"; shift 2 ;;
+    -v | --verbose ) VERBOSE=1; shift ;;
     -- ) shift; break ;;
     * ) break ;;
   esac
@@ -69,13 +100,13 @@ done
 ## input version tag overrides use of branch if present
 [[ -z "${RELEASE_TAG}" ]] && BRANCH_TAG="${RELEASE_BRANCH}" || BRANCH_TAG="${RELEASE_TAG}"
 
-
-
 ##  MAIN BODY OF SCRIPT
 
 ## date tag is YearMontDayHourMinuteSecondMicrosecond aka jid
 date_long=$(date +%Y%m%d%H%M%S%N)
 curr_date="${date_long::-2}"
+
+CURRDIR=$(pwd)
 
 PILLAR_DIR='/srv/pillar'
 PILLAR_AUTO_SETUP_DIR="auto_setup"
@@ -92,6 +123,37 @@ cat <<@EOF > "${PILLAR_AUTO_SETUP_TAG_ABSFILE}"
 @EOF
 
 
+# set logging infomation
+## want verbose while developing
+LOGGING="/dev/null"
+
+## log_file_format="${CURRDIR}/$0-${curr_date}.log"
+log_file_format="/var/log/salt/$0-${curr_date}.log"
+log_file="`date \"+${log_file_format}\"`"
+
+if [[ ${VERBOSE} -ne 0 ]];then
+    LOGGING="${log_file}"
+else
+    LOGGING="/dev/null"
+fi
+
+
+_display "$0: nightly build started"
+
+
 salt ${CODE_MINION} saltutil.refresh_pillar
 salt ${CODE_MINION} state.sls auto_setup
+
+_display "$0: nightly build checked out and modified salt from '${BRANCH_TAG} and about to build via orchstration"
+
+## salt-run --async state.orchestrate auto_setup.orch.build_platform_rh7
+## salt-run --async state.orchestrate auto_setup.orch.build_platform_deb8
+## salt-run --async state.orchestrate auto_setup.orch.build_platform_ub1604
+
+salt-run state.orchestrate auto_setup.orch.build_platform_rh7
+salt-run state.orchestrate auto_setup.orch.build_platform_deb8
+salt-run state.orchestrate auto_setup.orch.build_platform_ub1604
+
+_display "$0: nightly build finished"
+
 
