Ensure highstate finishes before signing by use of require

diff --git a/file_roots/auto_setup/nightly_bld b/file_roots/auto_setup/nightly_bld
--- a/file_roots/auto_setup/nightly_bld
+++ b/file_roots/auto_setup/nightly_bld
@@ -44,8 +44,8 @@ _usage() {
     echo "  -b, --branch    git HEAD of branch for specified major version, default 2016.11"
     echo "  -h, --help      this message"
     echo "  -m. --minion    salt-minion installed on salt-master node to use for code checkout, default 'm7m'"
+    echo "  -v, --verbose   verbose output"
 ##    echo "  -t, --tag       build's tag, e.g. v2016.11.1  for specific release version"
-##     echo "  -v, --verbose   verbose output"
 ##     echo "  -d, --debug     debug output enabled"
 ##    echo "  -l, --log       logging mode"
     echo ""
@@ -61,6 +61,7 @@ _usage() {
     echo "  salt-minion installed on salt-master node, id 'm7m'"
     echo ""
 }
+
 
 VERBOSE=0
 DEBUG=false
@@ -127,9 +128,12 @@ cat <<@EOF > "${PILLAR_AUTO_SETUP_TAG_ABSFILE}"
 ## want verbose while developing
 LOGGING="/dev/null"
 
+SCRIPTNAME=$(basename "$0")
+
 ## log_file_format="${CURRDIR}/$0-${curr_date}.log"
-log_file_format="/var/log/salt/$0-${curr_date}.log"
-log_file="`date \"+${log_file_format}\"`"
+## log_file_format="/var/log/salt/$SCRIPTNAME-${curr_date}.log"
+## log_file="`date \"+${log_file_format}\"`"
+log_file="/var/log/salt/$SCRIPTNAME-${curr_date}.log"
 
 if [[ ${VERBOSE} -ne 0 ]];then
     LOGGING="${log_file}"
@@ -138,22 +142,43 @@ else
 fi
 
 
-_display "$0: nightly build started"
+_display "$SCRIPTNAME: nightly build started"
 
 
-salt ${CODE_MINION} saltutil.refresh_pillar
-salt ${CODE_MINION} state.sls auto_setup
+salt ${CODE_MINION} saltutil.refresh_pillar || {
+    error "$SCRIPTNAME: refresh pillar for ${BRANCH_TAG}, retcode '${$?}'";
+}
 
-_display "$0: nightly build checked out and modified salt from '${BRANCH_TAG} and about to build via orchstration"
+salt ${CODE_MINION} state.sls auto_setup || {
+    error "$SCRIPTNAME:state for auto_setup failed to function for ${BRANCH_TAG}, retcode '${$?}'";
+}
+
+_display "$SCRIPTNAME: nightly build checked out and modified salt from '${BRANCH_TAG} and about to build via orchstration"
 
 ## salt-run --async state.orchestrate auto_setup.orch.build_platform_rh7
 ## salt-run --async state.orchestrate auto_setup.orch.build_platform_deb8
 ## salt-run --async state.orchestrate auto_setup.orch.build_platform_ub1604
 
-salt-run state.orchestrate auto_setup.orch.build_platform_rh7
-salt-run state.orchestrate auto_setup.orch.build_platform_deb8
-salt-run state.orchestrate auto_setup.orch.build_platform_ub1604
+salt-run state.orchestrate auto_setup.orch.build_platform_rh7 || {
+    error "$SCRIPTNAME:orch for build_platform_rh7 failed to build ${BRANCH_TAG}, retcode '${$?}'";
+}
 
-_display "$0: nightly build finished"
+salt-run state.orchestrate auto_setup.orch.build_platform_deb8 || {
+    error "$SCRIPTNAME:orch for build_platform_deb8 failed to build ${BRANCH_TAG}, retcode '${$?}'";
+}
+
+salt-run state.orchestrate auto_setup.orch.build_platform_deb7 || {
+    error "$SCRIPTNAME:orch for build_platform_deb7 failed to build ${BRANCH_TAG}, retcode '${$?}'";
+}
+
+salt-run state.orchestrate auto_setup.orch.build_platform_ub1604 || {
+    error "$SCRIPTNAME:orch for build_platform_ub1604 failed to build ${BRANCH_TAG}, retcode '${$?}'";
+}
+
+salt-run state.orchestrate auto_setup.orch.build_platform_ub1404 || {
+    error "$SCRIPTNAME:orch for build_platform_ub1404 failed to build ${BRANCH_TAG}, retcode '${$?}'";
+}
+
+_display "$SCRIPTNAME: nightly build finished"
 
 
